/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "background": "#f5f7f8",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#6bfe9c",
        "inverse-surface": "#0b0f10",
        "outline": "#747778",
        "surface-container-high": "#dfe3e4",
        "tertiary-dim": "#005867",
        "primary-fixed-dim": "#5bef90",
        "on-tertiary": "#ddf7ff",
        "on-tertiary-fixed": "#00333d",
        "surface-variant": "#d9dddf",
        "on-secondary-fixed": "#004930",
        "primary": "#006a35",
        "on-tertiary-fixed-variant": "#005361",
        "on-secondary-fixed-variant": "#006946",
        "tertiary-fixed": "#00dcff",
        "surface-container-highest": "#d9dddf",
        "on-secondary": "#c9ffdf",
        "on-primary-fixed-variant": "#006a35",
        "error-dim": "#9f0519",
        "on-secondary-container": "#005e3e",
        "secondary": "#006946",
        "secondary-fixed": "#72fbbd",
        "on-background": "#2c2f30",
        "secondary-container": "#72fbbd",
        "on-primary": "#cdffd4",
        "primary-container": "#6bfe9c",
        "error-container": "#fb5151",
        "on-primary-container": "#005f2f",
        "primary-fixed": "#6bfe9c",
        "secondary-dim": "#005c3d",
        "inverse-on-surface": "#9a9d9e",
        "error": "#b31b25",
        "surface-container-low": "#eef1f2",
        "surface-tint": "#006a35",
        "surface": "#f5f7f8",
        "tertiary-container": "#00dcff",
        "primary-dim": "#005c2d",
        "outline-variant": "#abadae",
        "on-surface": "#2c2f30",
        "on-tertiary-container": "#004956",
        "tertiary-fixed-dim": "#00cdee",
        "surface-container": "#e5e9ea",
        "surface-bright": "#f5f7f8",
        "on-error-container": "#570008",
        "tertiary": "#006576",
        "surface-dim": "#d0d5d7",
        "secondary-fixed-dim": "#63ecaf",
        "on-error": "#ffefee",
        "on-primary-fixed": "#004a23",
        "on-surface-variant": "#595c5d"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
